### PR TITLE
Changes to handle logo file name collision at root (assets) and in images directory

### PR DESCRIPTION
**Pull request by suskumar-MSFT**

### CODE REVIEW

**Comment by MikeStall** [comment]
What was the issue here? If there's already a file named "logo.jpg" in the assets?

**Comment by suskumar-MSFT** [comment]
We were skipping to add this file to the _resourceJson.Resources


---
In reply to: [880927302](https://github.com/microsoft/PowerApps-Language-Tooling/pull/277#issuecomment-880927302) [](http://example.com/codeflow?ancestors=880927302,880927302)

**Comment by lesaltzm** [comment]
> We were skipping to add this file to the _resourceJson.Resources
> 
> In reply to: [880927302](https://github.com/microsoft/PowerApps-Language-Tooling/pull/277#issuecomment-880927302)

Right, the logo file is stored in PublishInfo.json for some reason. ☹️

**Review by MikeStall — APPROVED** [review]
:shipit:

**Pull request merged**
